MyProjectMainBundle_homepage:
    pattern:  /
    defaults: { _controller: MyProjectMainBundle:Default:index}
MyProjectMainBundle_contacts:
    pattern:  /contacts
    defaults: { _controller: MyProjectMainBundle:Default:contacts }

MyProjectMainBundle_order:
    pattern:  /order
    defaults: { _controller: MyProjectMainBundle:Order:index }
MyProjectMainBundle_category:
    pattern:  /{slug}
    defaults: { _controller: MyProjectMainBundle:Default:category, slug: null }
